name: Deployment To AWS EC2
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
concurrency:
  group: build-and-test
  #cancel-in-progress: true
  
jobs:

  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: docker build
        run: docker build -t spm:'latest' .

      - name: docker login
        run: docker login --username 'aajahid' --password '${{secrets.DOCKER_PASSWORD}}'

      - name: tag docker image
        run: docker tag spm:'latest' '${{secrets.DOCKER_USERNAME}}'/spm:'latest'

      - name: push docker image
        run: docker push '${{secrets.DOCKER_USERNAME}}'/spm:'latest'
        

